### ISSUE TITLE
About the running of multiple fuzzing instances of the afl_integration.

### ISSUE THREAD

**Issue by QRXqrx** [Dongdongshe/K-Scheduler#17]
Hi there,

I have read your paper. K-scheduler is indeed an interesting work. I'm now trying to run the afl integration of K-scheduler following the instructions given in your [document](https://github.com/Dongdongshe/K-Scheduler/blob/main/afl_integration/build_example/README(non_wrapper%20based%20program).md). According to the scripts attached bellow, it seems I should start one process to run katz computation and another process to run fuzzing.  Do I have to run multiple katz computation instances if I want to run multiple fuzzing instances at once? If so, how to make different fuzzing instances to identify their own katz computation process?

```shell
cd [path to K-Schduler repo]/K-Scheduler/qsym_integration/build_example/
# clean fuzzer corpus and other meta data generated by fuzzer
rm -rf afl_out_* cur_coverage dyn_katz_cent
# reset signal file for graph computation module
echo 0 > signal
# run libfuzzer_kscheduler
./afl-fuzz_kscheduler -i seeds/ -o afl_out_cent -d -m none ./size @@
```

**Comment by Dongdongshe** [comment]
Hi, 

Each instance of K-scheduler requires two processes (afl fuzzer and katz computation process) **running in the same directory**. If you want to run multiple instances, **put each instance in a separate directory**. For example, say you want to run two instances, then you need to create two directories called instance_1 and instance_2. At each directory, you run two processes.

**Comment by QRXqrx** [comment]
Thanks! I will try it out! :-)
