### ISSUE TITLE
interprocedure graph problem

### ISSUE THREAD

**Issue by egoterm** [Dongdongshe/K-Scheduler#3]
你好，我用k-scheduler来测试binutils，但是在调用gen_graph.py生成全局CFG时发现readelf、objdump的IR中并没有llvm.compiler.used。想问一下gen_graph.py只能为C++程序生成inter procedure CFG吗？

**Comment by Dongdongshe** [comment]
K-scheduler可以同时支持C和C++。compile non_wrapper based program ，比如binutils ，请参考教程https://github.com/Dongdongshe/K-Scheduler/blob/main/afl_integration/build_example/README(non_wrapper%20based%20program).md
