### ISSUE TITLE
build harfbuzz fuzzer wrapper problem

### ISSUE THREAD

**Issue by mo718** [Dongdongshe/K-Scheduler#4]
请问为什么不能运行？
![1](https://user-images.githubusercontent.com/64512529/169292272-2912367d-0c7e-4211-b2f2-aef59c36e31e.png)

**Comment by Dongdongshe** [comment]
从报错的信息来看，"-c: command not found" 表明bash 把"-c" parse成了command name. 说明$CXX和$CXXFLAGS可能被错误的设置成了NULL。请再检查一下CXX和CXXFLAGS是否正确设置。可以加一个verbose option "-v" 帮助你debug.
