### ISSUE TITLE
Problem about running K-Scheduler-based afl on an example program harfbuzz

### ISSUE THREAD

**Issue by Jqqzzz** [Dongdongshe/K-Scheduler#5]
When I execute the last command in step **4.Build harfbuzz following Google FuzzBench settings** `$CXX $CXXFLAGS -std=c++11 -I ~/harfbuzz_BUILD/src/ ~/harfbuzz_BUILD/test/fuzzing/hb-fuzzer.o ~/harfbuzz_BUILD/src/.libs/libharfbuzz-fuzzing.a afl_llvm_rt_driver.a -o harfbuzz_afl_asan` about **Run K-Scheduler-based afl on an example program harfbuzz**，it tells me `clang-11: error: no such file or directory: '/home/jq/harfbuzz_BUILD/src/.libs/libharfbuzz-fuzzing.a'`. 
Can you help me?
![image](https://user-images.githubusercontent.com/30170232/169526855-6eb20005-33e7-41cf-aa86-7a5d1f64b391.png)

**Comment by Dongdongshe** [comment]
According to the error message "No such file libharfbuzz-fuzzing.a", it seems harfbuzz library libharfbuzz-fuzzing.a is not successfully built. Please double check if you follow the latest tutorials in https://github.com/Dongdongshe/K-Scheduler/blob/main/afl_integration/build_example/README.md. 

    ```sh
    # download harfbuzz source code
    git clone https://github.com/behdad/harfbuzz.git
    cd harfbuzz && git checkout f73a87d9a8c76a181794b74b527ea268048f78e3
    cd .. && cp -r harfbuzz BUILD
    # configure and build harfbuzz
    (cd ./src/hb-ucdn && CCLD="$CXX $CXXFLAGS" make)
    cd BUILD && ./autogen.sh && CCLD="$CXX $CXXFLAGS" ./configure --enable-static --disable-shared && make -j -C src fuzzing && cd ..
    # build harfbuzz fuzzer wrapper
    $CXX $CXXFLAGS -c -std=c++11 -I BUILD/src/ BUILD/test/fuzzing/hb-fuzzer.cc -o BUILD/test/fuzzing/hb-fuzzer.o 
    # link harfbuzz fuzzer wrapper with afl driver
    $CXX $CXXFLAGS -std=c++11 -I BUILD/src/ BUILD/test/fuzzing/hb-fuzzer.o BUILD/src/.libs/libharfbuzz-fuzzing.a afl_llvm_rt_driver.a -o harfbuzz_afl_asan
    ```

**Comment by Jqqzzz** [comment]
After I added a command `make` in `BUILD/src`, it executed successfully.
