### ISSUE TITLE
How do I set up the graph analysis module when running multiple K-Schedulers at the same time

### ISSUE THREAD

**Issue by egoterm** [Dongdongshe/K-Scheduler#9]
Hi, Im using K-scheduler to fuzz several programs(such as sqlite, tiff2pdf, tiff2bw), I want to test the performance of the K-scheduler by repeating my experiment for 10 times on each target. But i dont know how to set graph analysis module when I running multiple K-scheduler at the same time. 
According to [your issue](https://github.com/Dongdongshe/K-Scheduler/blob/main/afl_integration/build_example/README(non_wrapper%20based%20program).md), I opened 10 shells to run gen_dyn_weight.py, but how do I make each python script correspond to each k-scheduler that is running?

**Comment by Dongdongshe** [comment]
1. Create a directory for each fuzzing repetition. In your cases, that is rep1, rep2, ..., rep10. 
2. Put gen_dyn_weight.py, afl_fuzz_kscheduler along with other graph data files in every directory.
3. Open 20 terminals or write a python script to run 10 fuzzers and 10 corresponding gen_dyn_weight.py. Make sure you enter the correct directory before running afl-fuzz-kscheduler or gen_dyn_weight.py

**Comment by egoterm** [comment]
Thanks, but I met another problem when I tried to run K-scheduler. I followed your advice to put python script, graph files and afl_fuzz_kscheduler in every directory. But when I ran k-scheduler, the stats showed that the exec speed of fuzzer is 0.
`exec speed : 0.00/sec (zzzz...)`
The output of python script is :
`covered 47 node, generate new graph.`
My directory:
`afl-fuzz_kscheduler  border_edges     child_node    dyn_katz_cent      graph_data_pack  parent_node     readelf.ll
afl_out_cent         cfg_out_readelf  cur_coverage  gen_dyn_weight.py  katz_cent        readelf_fix.ll  signal`
The number of edges:
`wc -l katz_cent: 42456 katz_cent`
I don't understand why fuzzer doesn't execute input after running for a few seconds.
Look forward to your reply. Thank you very much

**Comment by egoterm** [comment]
By the way, the input seeds that I used is the default seeds provided by afl.

**Comment by Dongdongshe** [comment]
1. It seems the binary is not properly built. Please check a detailed tutorial on how to build binary with kscheduler on binutils (including readelf) in https://github.com/Dongdongshe/K-Scheduler/blob/main/afl_integration/build_example/README(non_wrapper%20based%20program).md.
2. The input seed is orthogonal to kscheduler since it is a light-weight data-driven solution without any ML model training.
